spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/task_management?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: myheadpounds16D
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#app:
#  jwt:
#    secret: "SomeSecretKeyoidhujh9jkoi9ydhuj534nh89jjnhs7xvjmhziklogjmmskmrpojksgns8ejHUYhfnnbythbfhjz7lUHNN89f79gin58ujmgnbn"
#    tokenExpiration: 300m
#    refreshTokenExpiration: 30m