version: '3'
services:
  postgres:
    image: postgres:12.3
    ports:
      - "5434:5434"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_db