version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=task_management
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: